spring.application.name=ProductRecommend
spring.datasource.url = jdbc:postgresql://localhost:5433/employeedb
spring.datasource.username = postgres
spring.datasource.password = disha24
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8085