spring.application.name=ProductGateway
server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Product Service
spring.cloud.gateway.routes[0].id=product-catalogue-service
spring.cloud.gateway.routes[0].uri=lb://ProductCatalogue
spring.cloud.gateway.routes[0].predicates[0]=Path=/catalogs/products/**

spring.cloud.gateway.routes[1].id=product-stock-service
spring.cloud.gateway.routes[1].uri=lb://ProductStock
spring.cloud.gateway.routes[1].predicates[0]=Path=/Stock/**

spring.cloud.gateway.routes[2].id=product-price-service
spring.cloud.gateway.routes[2].uri=lb://ProductPrice
spring.cloud.gateway.routes[2].predicates[0]=Path=/Price/**

spring.cloud.gateway.routes[3].id=cart-service
spring.cloud.gateway.routes[3].uri=lb://ProductPrice
spring.cloud.gateway.routes[3].predicates[0]=Path=/carts/**

spring.cloud.gateway.routes[4].id=recommendation-service
spring.cloud.gateway.routes[4].uri=lb://ProductRecommend
spring.cloud.gateway.routes[4].predicates[0]=Path=/recommend/**                                          
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always